/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThresholdsRouteImport } from './routes/thresholds'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as LiveRouteImport } from './routes/live'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'

const ThresholdsRoute = ThresholdsRouteImport.update({
  id: '/thresholds',
  path: '/thresholds',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/metrics': typeof MetricsRoute
  '/notes': typeof NotesRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/thresholds': typeof ThresholdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/metrics': typeof MetricsRoute
  '/notes': typeof NotesRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/thresholds': typeof ThresholdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/live': typeof LiveRoute
  '/metrics': typeof MetricsRoute
  '/notes': typeof NotesRoute
  '/patients': typeof PatientsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/thresholds': typeof ThresholdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/live'
    | '/metrics'
    | '/notes'
    | '/patients'
    | '/reports'
    | '/settings'
    | '/thresholds'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/live'
    | '/metrics'
    | '/notes'
    | '/patients'
    | '/reports'
    | '/settings'
    | '/thresholds'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/live'
    | '/metrics'
    | '/notes'
    | '/patients'
    | '/reports'
    | '/settings'
    | '/thresholds'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LiveRoute: typeof LiveRoute
  MetricsRoute: typeof MetricsRoute
  NotesRoute: typeof NotesRoute
  PatientsRoute: typeof PatientsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  ThresholdsRoute: typeof ThresholdsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thresholds': {
      id: '/thresholds'
      path: '/thresholds'
      fullPath: '/thresholds'
      preLoaderRoute: typeof ThresholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LiveRoute: LiveRoute,
  MetricsRoute: MetricsRoute,
  NotesRoute: NotesRoute,
  PatientsRoute: PatientsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  ThresholdsRoute: ThresholdsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
